version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:ythrM0FVXk9j5bGnyDyXg82t4ancMXDhLKqvmGDHD5k=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ecommerceapi
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=your-database
      - MYSQL_USER=your-username
      - MYSQL_PASSWORD=your-password
      - MYSQL_ROOT_PASSWORD=root-password
